using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
// ReSharper disable InconsistentNaming
// ReSharper disable MemberHidesStaticFromOuterClass
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elision.Feature.Library.Search
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{6DAD8E76-DA0D-4093-9E8C-D4162A23C562}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureLibrarySearch/Base/_Searchable</description></item>
        /// </list>
        /// </summary>
        public struct _Searchable
        {
            public static readonly ID TemplateId = new ID("{6DAD8E76-DA0D-4093-9E8C-D4162A23C562}");
            public const string Name = "_Searchable";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Checkbox</description></item>
                ///     <item><term>Field ID:</term><description>{3C4D4755-8FB1-40F2-B236-BE1E0B552A84}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureLibrarySearch/Base/_Searchable/Search/HideFromSearchResults</description></item>
                /// </list>
                /// </summary>
                public static readonly ID HideFromSearchResults = new ID("{3C4D4755-8FB1-40F2-B236-BE1E0B552A84}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Checkbox</description></item>
                ///     <item><term>Field ID:</term><description>{3C4D4755-8FB1-40F2-B236-BE1E0B552A84}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Feature/ElisionFeatureLibrarySearch/Base/_Searchable/Search/HideFromSearchResults</description></item>
                /// </list>
                /// </summary>
                public const string HideFromSearchResults = "HideFromSearchResults";
            }
		}
    }
}
